services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./app
          target: /code/app
        - action: rebuild
          path: ./requirements.txt 
          target: /code/requirements.txt